ARDUINO_DIR = ${ARDUINO_HOME}
                                            
TARGET       = led-wall
MCU          = atmega328p
F_CPU        = 16000000                         
ARDUINO_PORT = /dev/ttyUSB0
AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF   = $(ARDUINO_DIR)/hardware/tools/avrdude.conf
                                            
ARDUINO_LIBS = 
                                            
include Arduino.mk
